environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
    - nodejs_version: "13"
    - nodejs_version: "14"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci
  - npm run ctest
  - npm run wtest
  - npm run ftest
