language: node_js
dist: bionic
addons:
  apt:
    packages:
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - xvfb
notifications:
  email: false
cache:
  directories:
    - node_modules
script:
  - "npm run build"
  - "npm run lint"
  - "xvfb-run --auto-servernum npm run unit"
  - "xvfb-run --auto-servernum npm run funit"
  - "xvfb-run --auto-servernum npm run wunit"
jobs:
  include:
    - node_js: "12"
