language: node_js
dist: bionic
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      # - libnss3
      # This is required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "npm run build"
  - "npm run unit"
  - "npm run funit"
  - "npm run wunit"
jobs:
  include:
    - node_js: "10.17.0"
