name: Regression
description: Functionality that used to work and does not any more
title: "[Regression]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version-good
    attributes:
      label: Good Playwright version
      description: Which version of of Playwright the functionality was working as expected?
      placeholder: ex. 1.12.0
    validations:
      required: true
  - type: input
    id: version-bad
    attributes:
      label: Bad Playwright version
      description: Which version of of Playwright the functionality was not working anymore?
      placeholder: ex. 1.13.0
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you running Playwright on?
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: ex. Browser, Node.js version, Linux distribution etc.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? / Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: Code snippet to reproduce your bug
      description: Help us help you! Put down a short code snippet that illustrates your bug and that we can run and debug locally. This will be automatically formatted into code, so no need for backticks.
      render: shell
      value: |
        const { chromium, webkit, firefox } = require('playwright');

        (async () => {
          const browser = await chromium.launch();
          // ...
        })();
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

