name: mirror chromium

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/mirror_chromium_to_cdn.yml'
      - 'browser_patches/chromium/BUILD_NUMBER'

env:
  AZ_ACCOUNT_KEY: ${{ secrets.AZ_ACCOUNT_KEY }}
  AZ_ACCOUNT_NAME: ${{ secrets.AZ_ACCOUNT_NAME }}
  TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  ubuntu_18_04:
    name: all platforms
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: ./browser_patches/checkout_build_archive_upload.sh chromium-linux-mirror-to-cdn
    - run: ./browser_patches/checkout_build_archive_upload.sh chromium-mac-mirror-to-cdn
    - run: ./browser_patches/checkout_build_archive_upload.sh chromium-win32-mirror-to-cdn
    - run: ./browser_patches/checkout_build_archive_upload.sh chromium-win64-mirror-to-cdn

