name: "N-1 on example"
on: workflow_dispatch
jobs:
  test_n_minus_one:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash; export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    - run: nvm use 16
    - run: cd examples/todomvc; npm install
    - run: cd examples/todomvc; npx playwright install
    - run: cd examples/todomvc; npm test
