name: "N-1 on example"
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  test_n_minus_one: #test that an older, pinned playwright/test dependency is able to use npx playwright install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: cd examples/todomvc; npm install
    - run: cd examples/todomvc; npx playwright install
    - run: cd examples/todomvc; npm run ctest
