name: "devrelease"

on:
  push:
    branches:
      - master
      - release-*
    paths:
      - docs/docker/**
      - browsers.json

jobs:
  publish-canary-docker:
    name: "publish to DockerHub"
    runs-on: ubuntu-18.04
    if: github.repository == 'microsoft/playwright'
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: playwright.azurecr.io
        username: playwright
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm ci
    - run: npm run build
    - name: docker: build & publish
      run: |
        # build docker image
        ./docs/docker/build.sh
        # tag image accordingly
        docker tag playwright:localbuild public/playwright:next
        docker tag playwright:localbuild public/playwright:sha-${{ github.sha }}
        docker rmi playwright:localbuild
        # push image to registry
        docker push public/playwright:next

