name: "tests 1"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths-ignore:
      - 'browser_patches/**'
      - 'docs/**'
    branches:
      - main
      - release-*

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING_2: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }} - Node.js ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-20.04]
        node-version: [14]
        include:
          - os: ubuntu-20.04
            node-version: 12
            browser: chromium
          - os: ubuntu-20.04
            node-version: 16
            browser: chromium
          - os: ubuntu-20.04
            node-version: 18
            browser: chromium
    runs-on: ${{ matrix.os }}
    steps:
    - run: env
