name: "Docker tests"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths:
      - '.github/workflows/tests_docker.yml'
      - '**/Dockerfile*'
      - 'browsers.json'
      - 'package.json'
    branches:
      - main
      - release-*

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  test_linux_docker:
    name: "Docker ${{ matrix.os_name}} ${{ matrix.arch}} ${{ matrix.user }} Tests"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - os_name: "Ubuntu 18.04"
          tag: bionic
          user: pwuser
          arch: amd64
        - os_name: "Ubuntu 20.04"
          tag: focal
          user: root
          arch: arm64
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm i -g npm@8
    - run: npm ci
    - run: npm run build
    - run: ./utils/docker/build.sh --${{ matrix.arch }} ${{ matrix.tag }} playwright:localbuild
    - name: Launch container
      run: |
        docker run \
          --rm \
          --name docker-tests \
          --platform linux/${{ matrix.arch }} \
          --user=${{ matrix.user }} \
          --workdir /home/pwuser \
          --env CI \
          --env INSIDE_DOCKER=1 \
          -d \
          -t \
          playwright:localbuild /bin/bash
    - name: Clone inside docker
      run: |
        docker exec docker-tests /bin/bash -c '
          git clone https://github.com/microsoft/playwright
          cd playwright
          git checkout ${{ env.GITHUB_SHA }}
          git show
        '
    - name: Run "npm ci" inside docker
      run: docker exec --workdir /home/pwuser/playwright docker-tests npm ci
    - name: Run "npm run build" inside docker
      run: docker exec --workdir /home/pwuser/playwright docker-tests npm run build
    - name: Run "npm run test" inside docker
      run: docker exec --workdir /home/pwuser/playwright docker-tests xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npm run test
    - name: Copy test results from container
      run: docker cp docker-tests:/home/pwuser/playwright/test-results ./test-results
      if: always()
    - name: Stop container
      if: always()
      run: docker kill docker-tests
    - name: Upload Flakiness dashboard
      run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
    - name: Upload Github Artifacts
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: docker-ubuntu-${{ matrix.tag }}-${{ matrix.arch }}-${{ matrix.user }}-test-results
        path: test-results

