name: "tests 2"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths-ignore:
      - 'browser_patches/**'
      - 'docs/**'
    branches:
      - main
      - release-*


env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  headed_tests:
    name: "headed ${{ matrix.browser }} (${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm i -g npm@8
    - run: npm ci
      env:
        DEBUG: pw:install
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test -- --project=${{ matrix.browser }} --headed
      if: always() && startsWith(matrix.os, 'ubuntu-')
    - run: npm run test -- --project=${{ matrix.browser }} --headed
      if: always() && !startsWith(matrix.os, 'ubuntu-')
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
      shell: bash
    - uses: actions/upload-artifact@v1
      if: always() && startsWith(matrix.os, 'ubuntu-')
      with:
        name: headful-${{ matrix.browser }}-linux-test-results
        path: test-results
