name: "tests 1"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths-ignore:
      - 'browser_patches/**'
      - 'docs/**'
    branches:
      - main
      - release-*

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }} - Node.js ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-22.04]
        node-version: [16]
        include:
          - os: ubuntu-22.04
            node-version: 18
            browser: chromium
          - os: ubuntu-22.04
            node-version: 20
            browser: chromium
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      env:
        DEBUG: pw:install
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test -- --project=${{ matrix.browser }}
      env:
        PWTEST_BLOB_REPORT_NAME: "${{ matrix.browser }}-${{ matrix.os }}-node${{ matrix.node-version }}"
    - run: node tests/config/checkCoverage.js ${{ matrix.browser }}
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
      shell: bash
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: blob-report

  test_linux_chromium_tot:
    name: ${{ matrix.os }} (chromium tip-of-tree)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      env:
        DEBUG: pw:install
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: npx playwright install --with-deps chromium-tip-of-tree
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test -- --project=chromium
      env:
        PWTEST_CHANNEL: chromium-tip-of-tree
        PWTEST_BLOB_REPORT_NAME: "${{ matrix.os }}-chromium-tip-of-tree"
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
      shell: bash
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: blob-report

  test_test_runner:
    name: Test Runner
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16]
        shard: [1/2, 2/2]
        coverage: [""]
        include:
          - os: ubuntu-latest
            node-version: 18
            shard: 1/2
            coverage: "1"
          - os: ubuntu-latest
            node-version: 18
            shard: 2/2
            coverage: "1"
          - os: ubuntu-latest
            node-version: 20
            shard: 1/2
            coverage: ""
          - os: ubuntu-latest
            node-version: 20
            shard: 2/2
            coverage: ""
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - run: npm ci
      env:
        DEBUG: pw:install
    - run: npm run build -- --sourcemap
    - run: npx playwright install --with-deps
    - run: echo "PWTEST_COVERAGE=${{ matrix.coverage }}" >> "$GITHUB_ENV"
      if: github.event_name == 'push'
    - run: npm run ttest -- --shard ${{ matrix.shard }}
      env:
        PWTEST_BLOB_REPORT_NAME: "${{ matrix.os }}-node${{ matrix.node-version }}"
      if: matrix.os != 'ubuntu-latest'
    - run: xvfb-run npm run ttest --  --shard ${{ matrix.shard }}
      env:
        PWTEST_BLOB_REPORT_NAME: "${{ matrix.os }}-node${{ matrix.node-version }}"
      if: matrix.os == 'ubuntu-latest'
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
      shell: bash
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: blob-report
    - name: Upload coverage data to GitHub
      if: always() && github.event_name == 'push' && matrix.coverage == '1'
      uses: actions/upload-artifact@v3
      with:
        name: ttest-coverage
        path: ./test-results/coverage-data
        retention-days: 1

  test_web_components:
    name: Web Components
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      env:
        DEBUG: pw:install
    - run: npm run build

    - run: npx playwright install --with-deps
    - run: npm run test-html-reporter
      env:
        PWTEST_BLOB_REPORT_NAME: "web-components-html-reporter"
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: packages/html-reporter/blob-report

    - run: npm run test-web
      if: always()
      env:
        PWTEST_BLOB_REPORT_NAME: "web-components-web"
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: packages/web/blob-report

  test_vscode_extension:
    name: VSCode Extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      env:
        DEBUG: pw:install
    - run: npm run build
    - run: npx playwright install chromium
    - name: Checkout extension
      run: git clone https://github.com/microsoft/playwright-vscode.git
    - name: Print extension revision
      run: git rev-parse HEAD
      working-directory: ./playwright-vscode
    - name: Remove @playwright/test from extension dependencies
      run: node -e "const p = require('./package.json'); delete p.devDependencies['@playwright/test']; fs.writeFileSync('./package.json', JSON.stringify(p, null, 2));"
      working-directory: ./playwright-vscode
    - name: Build extension
      run: npm install && npm run build
      working-directory: ./playwright-vscode
    - name: Run extension tests
      run: npm run test -- --workers=1
      env:
        PWTEST_BLOB_REPORT_NAME: "vscode-extension"
      working-directory: ./playwright-vscode
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: ./playwright-vscode/blob-report

  test_package_installations:
    name: "Installation Test ${{ matrix.os }}"
    runs-on: ${{ matrix.os  }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      env:
        DEBUG: pw:install
    - run: npm run build
    - run: npx playwright install-deps
    - run: npm run itest
      if: matrix.os != 'ubuntu-latest'
      env:
        PWTEST_BLOB_REPORT_NAME: "package-installations-${{ matrix.os }}"
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run itest
      if: matrix.os == 'ubuntu-latest'
      env:
        PWTEST_BLOB_REPORT_NAME: "package-installations-${{ matrix.os }}"
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
      shell: bash
    - name: Upload blob report
      if: always()
      uses: ./.github/actions/upload-blob-report
      with:
        report_dir: blob-report

  test_runner_coverage:
    name: "Test Runner Coverage Report"
    needs: test_test_runner
    if: ${{ always() }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build -- --sourcemap
    - name: Download coverage data from GitHub
      if: github.event_name == 'push'
      uses: actions/download-artifact@v3
      with:
        name: ttest-coverage-${{ github.run_attempt }}
        path: ./coverage-data
    - name: Generate coverage report
      run: node utils/generate_coverage_report.js ./coverage-data
      if: github.event_name == 'push'
    - name: Upload HTML report to Azure
      if: github.event_name == 'push'
      run: |
        azcopy cp --recursive "./coverage-report/*" "https://mspwblobreport.blob.core.windows.net/\$web/ttest-coverage"
        echo "Test Runner Coverage Report url: https://mspwblobreport.z1.web.core.windows.net/ttest-coverage/index.html"
      env:
        AZCOPY_AUTO_LOGIN_TYPE: SPN
        AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
        AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
        AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'
