name: "test Chrome Beta"

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    paths-ignore:
      - 'browser_patches/**'
    types: [ labeled ]
    branches:
      - master
      - release-*

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  chrome_beta_linux:
    name: "Linux"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./utils/install-chrome-beta/reinstall_linux.sh
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: node lib/cli/cli install-deps chromium
    - run: node lib/cli/cli install ffmpeg
    # XVFB-RUN merges both STDOUT and STDERR, whereas we need only STDERR
    # Wrap `npm run` in a subshell to redirect STDERR to file.
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- bash -c "npm run ctest -- --channel=chrome-beta"
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: chrome-beta-linux-test-results
        path: test-results

  chrome_beta_win:
    name: "Windows"
    runs-on: windows-latest
    steps:
    - name: Install Media Pack
      shell: powershell
      run: Install-WindowsFeature Server-Media-Foundation
    - name: Install Chrome Beta
      shell: powershell
      run: choco install -y googlechromebeta --pre --force
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: node lib/cli/cli install ffmpeg
    - run: npm run ctest -- --channel=chrome-beta
      shell: bash
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
      shell: bash
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: chrome-beta-win-test-results
        path: test-results

  chrome_beta_mac:
    name: "Mac 10.15"
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - run: ./utils/install-chrome-beta/reinstall_mac.sh
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: node lib/cli/cli install ffmpeg
    - run: npm run ctest -- --channel=chrome-beta
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: chrome-beta-mac-test-results
        path: test-results

