name: WebKit Tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install required packages
      run: |
        sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0
        sudo apt-get install xvfb

    - name: npm install, build, and test
      run: |
        npm install
        cd .local-webkit/linux-1046; ls -1 | LD_LIBRARY_PATH=$PWD xargs ldd
        npm run build
        DUMPIO=1 xvfb-run --auto-servernum npm run wunit
      env:
        CI: true
